{{- if .Values.secretProvider.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProvider.name | default "shopverse-secrets" | quote }}
  labels:
    app: shopverse
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: {{ .Values.secretProvider.keyVaultName | quote }}
    tenantId: {{ .Values.secretProvider.tenantId | quote }}
    objects: |
      array:
        {{- range .Values.secretProvider.secrets }}
        - |
          objectName: {{ .keyVaultSecretName | quote }}
          objectType: secret
        {{- end }}
  secretObjects:
    - secretName: {{ .Values.secret.name | default "shopverse-secret" | quote }}
      type: Opaque
      data:
        {{- range .Values.secretProvider.secrets }}
        - objectName: {{ .keyVaultSecretName | quote }}
          key: {{ .name | quote }}
        {{- end }}
{{- end }}
