{{- if .Values.secretProvider.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProvider.name | default "shopverse-secrets" | quote }}
  labels:
    app: shopverse
spec:
  provider: {{ .Values.secretProvider.provider | default "aws" }}
  parameters:
    objects: |
      {{- range .Values.secretProvider.secrets }}
      - objectName: {{ .secretArn | quote }}
        objectType: "secretsmanager"
      {{- end }}
  secretObjects:
    - secretName: {{ .Values.secret.name | default "shopverse-secret" | quote }}
      type: Opaque
      data:
        {{- range .Values.secretProvider.secrets }}
        - objectName: {{ .secretArn | quote }}
          key: {{ .name | quote }}
        {{- end }}
{{- end }}
