{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default "shopverse-secret" | quote }}
  labels:
    app: shopverse
type: Opaque
data:
  DB_PASSWORD: {{ ternary .Values.mysql.password .Values.database.password .Values.mysql.enabled | b64enc | quote }}
  {{- if .Values.mysql.enabled }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | b64enc | quote }}
  {{- end }}
  JWT_SECRET: {{ .Values.jwtSecret | b64enc | quote }}
{{- end }}
